// -------------------------------------------------------------------------------------------------
// <copyright file="CsprojectFile.cs" company="RHEA System S.A.">
//    Copyright (c) 2015-2020 RHEA System S.A.
//
//    Author: Sam Gerené, Alex Vorobiev, Merlin Bieze, Naron Phou, Patxi Ozkoidi, Alexander van Delft
//            Nathanael Smiechowski, Kamil Wojnowski
//
//    This file is part of CDP4-IME Community Edition. 
//    The CDP4-IME Community Edition is the RHEA Concurrent Design Desktop Application and Excel Integration
//    compliant with ECSS-E-TM-10-25 Annex A and Annex C.
//
//    The CDP4-IME Community Edition is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Affero General Public
//    License as published by the Free Software Foundation; either
//    version 3 of the License, or any later version.
//
//    The CDP4-IME Community Edition is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace CDP4PluginPackager.Models.Sdk
{
    using System;
    using System.Xml.Serialization;

    /// <summary>
    /// Autogenerated class matching a "PropertyGroup" tag in a Sdk style csproj file.
    /// </summary>
    [XmlRoot(ElementName = "PropertyGroup")]
    public class PropertyGroup
    {
        /// <summary>
        /// Gets or Sets the Condition
        /// </summary>
        [XmlAttribute(AttributeName = "Condition")]
        public string Condition { get; set; }

        /// <summary>
        /// Gets or Sets the Project Guid
        /// </summary>
        [XmlElement(ElementName = "ProjectGuid")]
        public string ProjectGuid { get; set; }

        /// <summary>
        /// Gets or Sets the Assembly Name
        /// </summary>
        [XmlElement(ElementName = "AssemblyName")]
        public string AssemblyName { get; set; }

        /// <summary>
        /// Gets or Sets the Target Framework
        /// </summary>
        [XmlElement(ElementName = "TargetFramework")]
        public string TargetFramework { get; set; }

        /// <summary>
        /// Gets or Sets the Assembly Title
        /// </summary>
        [XmlElement(ElementName = "AssemblyTitle")]
        public string AssemblyTitle { get; set; }

        /// <summary>
        /// Gets or Sets the Assembly Description
        /// </summary>
        [XmlElement(ElementName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets the Assembly Version
        /// </summary>
        [XmlElement(ElementName = "AssemblyVersion")]
        public string AssemblyVersion { get; set; }

        /// <summary>
        /// Gets or Sets the minimum assembly version
        /// </summary>
        [XmlElement(ElementName = "MinIMEVersion")]
        public string MinIMEVersion { get; set; }

        /// <summary>
        /// Gets or Sets the Output Path
        /// </summary>
        [XmlElement(ElementName = "OutputPath")]
        public string OutputPath { get; set; }
    }
}
