// -------------------------------------------------------------------------------------------------
// <copyright file="Configuration.cs" company="RHEA System S.A.">
//    Copyright (c) 2015-2020 RHEA System S.A.
// </copyright>
// <summary>
//   This file has been generated using a csproj file with this tool to convert Xml structure into Csharp: https://xmltocsharp.azurewebsites.net/
// </summary>
// -------------------------------------------------------------------------------------------------

namespace CDP4PluginPackager.Models.AutoGen
{
    using System.Xml.Serialization;

    /// <summary>
    /// Autogenerated class matching a "Configuration" tag in a csproj file
    /// </summary>
    [XmlRoot(ElementName = "Configuration", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public class Configuration
    {
        [XmlAttribute(AttributeName = "Condition")]
        public string Condition { get; set; }

        [XmlText]
        public string Text { get; set; }
    }
}
