// -------------------------------------------------------------------------------------------------
// <copyright file="Csc.cs" company="RHEA System S.A.">
//    Copyright (c) 2015-2020 RHEA System S.A.
// </copyright>
// <summary>
//   This file has been generated using a csproj file with this tool to convert Xml structure into Csharp: https://xmltocsharp.azurewebsites.net/
// </summary>
// -------------------------------------------------------------------------------------------------

namespace CDP4PluginPackager.Models.AutoGen
{
    using System.Xml.Serialization;

    /// <summary>
    /// Autogenerated class matching a "Csc" tag in a csproj file
    /// </summary>
    [XmlRoot(ElementName = "Csc", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public class Csc
    {
        [XmlAttribute(AttributeName = "ToolExe")]
        public string ToolExe { get; set; }

        [XmlAttribute(AttributeName = "ToolPath")]
        public string ToolPath { get; set; }

        [XmlAttribute(AttributeName = "YieldDuringToolExecution")]
        public string YieldDuringToolExecution { get; set; }
    }
}
