// -------------------------------------------------------------------------------------------------
// <copyright file="CsprojectFile.cs" company="RHEA System S.A.">
//    Copyright (c) 2015-2020 RHEA System S.A.
// </copyright>
// <summary>
//   This is an auto-generated class. Any manual changes on this file will be overwritten!
// </summary>
// -------------------------------------------------------------------------------------------------

namespace CDP4PluginPackager.Models.AutoGen
{
    using System.Collections.Generic;
    using System.Xml.Serialization;

    /// <summary>
    /// Autogenerated class matching a "Project" tag in a csproj file.
    /// This is the top container element
    /// </summary>
    [XmlRoot(ElementName = "Project", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public class CsprojectFile
    {
        [XmlElement(ElementName = "Import", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
        public List<Import> Import { get; set; }

        [XmlElement(ElementName = "PropertyGroup", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
        public List<PropertyGroup> PropertyGroup { get; set; }

        [XmlElement(ElementName = "ItemGroup", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
        public List<ItemGroup> ItemGroup { get; set; }

        [XmlElement(ElementName = "Target", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
        public Target Target { get; set; }

        [XmlAttribute(AttributeName = "ToolsVersion")]
        public string ToolsVersion { get; set; }

        [XmlAttribute(AttributeName = "xmlns")]
        public string Xmlns { get; set; }
    }
}
