// -------------------------------------------------------------------------------------------------
// <copyright file="Page.cs" company="RHEA System S.A.">
//    Copyright (c) 2015-2020 RHEA System S.A.
// </copyright>
// <summary>
//   This is an auto-generated class. Any manual changes on this file will be overwritten!
// </summary>
// -------------------------------------------------------------------------------------------------

namespace CDP4PluginPackager.Models.AutoGen
{
    using System.Xml.Serialization;

    /// <summary>
    /// Autogenerated class matching a "Page" tag in a csproj file
    /// </summary>
    [XmlRoot(ElementName = "Page", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public class Page
    {
        [XmlElement(ElementName = "Generator", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
        public string Generator { get; set; }

        [XmlElement(ElementName = "SubType", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
        public string SubType { get; set; }

        [XmlAttribute(AttributeName = "Include")]
        public string Include { get; set; }
    }
}
