// -------------------------------------------------------------------------------------------------
// <copyright file="ProjectReference.cs" company="RHEA System S.A.">
//    Copyright (c) 2015-2020 RHEA System S.A.
// </copyright>
// <summary>
//   This file has been generated using a csproj file with this tool to convert Xml structure into Csharp: https://xmltocsharp.azurewebsites.net/
// </summary>
// -------------------------------------------------------------------------------------------------

namespace CDP4PluginPackager.Models.AutoGen
{
    using System.Xml.Serialization;

    /// <summary>
    /// Autogenerated class matching a "ProjectReference" tag in a csproj file
    /// </summary>
    [XmlRoot(ElementName = "ProjectReference", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public class ProjectReference
    {
        [XmlElement(ElementName = "Project", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
        public string Project { get; set; }

        [XmlElement(ElementName = "Name", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
        public string Name { get; set; }

        [XmlElement(ElementName = "Private", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
        public string Private { get; set; }

        [XmlAttribute(AttributeName = "Include")]
        public string Include { get; set; }
    }
}
