// --------------------------------------------------------------------------------------------------------------------
// <copyright file="PropertyGroup.cs" company="RHEA System S.A.">
//    Copyright (c) 2015-2020 RHEA System S.A.
//
//    Author: Sam Gerené, Alex Vorobiev, Merlin Bieze, Naron Phou, Patxi Ozkoidi, Alexander van Delft, Mihail Militaru
//            Nathanael Smiechowski, Kamil Wojnowski
//
//    This file is part of CDP4-IME Community Edition. 
//    The CDP4-IME Community Edition is the RHEA Concurrent Design Desktop Application and Excel Integration
//    compliant with ECSS-E-TM-10-25 Annex A and Annex C.
//
//    The CDP4-IME Community Edition is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Affero General Public
//    License as published by the Free Software Foundation; either
//    version 3 of the License, or any later version.
//
//    The CDP4-IME Community Edition is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace CDP4PluginPackager.Models.AutoGen
{
    using System;
    using System.Xml.Serialization;

    /// <summary>
	/// Autogenerated class matching a "PropertyGroup" tag in a csproj file
	/// </summary>
	[XmlRoot(ElementName = "PropertyGroup", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
	public class PropertyGroup
	{
		[XmlElement(ElementName = "Configuration", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public Configuration Configuration { get; set; }

		[XmlElement(ElementName = "Platform", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public Platform Platform { get; set; }

		[XmlElement(ElementName = "ProjectGuid", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public Guid ProjectGuid { get; set; }

		[XmlElement(ElementName = "OutputType", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string OutputType { get; set; }

		[XmlElement(ElementName = "AppDesignerFolder", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string AppDesignerFolder { get; set; }

		[XmlElement(ElementName = "RootNamespace", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string RootNamespace { get; set; }

		[XmlElement(ElementName = "AssemblyName", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string AssemblyName { get; set; }

		[XmlElement(ElementName = "TargetFrameworkVersion", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string TargetFrameworkVersion { get; set; }

		[XmlElement(ElementName = "FileAlignment", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string FileAlignment { get; set; }

		[XmlElement(ElementName = "Deterministic", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string Deterministic { get; set; }

		[XmlElement(ElementName = "DebugSymbols", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string DebugSymbols { get; set; }

		[XmlElement(ElementName = "DebugType", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string DebugType { get; set; }

		[XmlElement(ElementName = "Optimize", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string Optimize { get; set; }

		[XmlElement(ElementName = "OutputPath", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string OutputPath { get; set; }

		[XmlElement(ElementName = "DefineConstants", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string DefineConstants { get; set; }

		[XmlElement(ElementName = "ErrorReport", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string ErrorReport { get; set; }

		[XmlElement(ElementName = "WarningLevel", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
		public string WarningLevel { get; set; }

		[XmlAttribute(AttributeName = "Condition")]
        public string Condition { get; set; }
	}
}

