// -------------------------------------------------------------------------------------------------
// <copyright file="Target.cs" company="RHEA System S.A.">
//    Copyright (c) 2015-2020 RHEA System S.A.
// </copyright>
// <summary>
//   This is an auto-generated class. Any manual changes on this file will be overwritten!
// </summary>
// -------------------------------------------------------------------------------------------------

namespace CDP4PluginPackager.Models.AutoGen
{
    using System.Xml.Serialization;

    /// <summary>
    /// Autogenerated class matching a "Target" tag in a csproj file
    /// </summary>
    [XmlRoot(ElementName = "Target", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public class Target
    {
        [XmlElement(ElementName = "Csc", Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
        public Csc Csc { get; set; }

        [XmlAttribute(AttributeName = "Name")]
        public string Name { get; set; }
    }
}
